---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: netbird-mgmt-api-key
    template:
      data:
        NB_API_KEY: "{{ .NB_API_KEY }}"
  dataFrom:
  - extract:
      key: netbird
