---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator
spec:
  chartRef:
    kind: OCIRepository
    name: netbird-operator
  interval: 1h
  values:
    cluster:
      name: homelab
    operator:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 256Mi
    webhook:
      enableCertManager: true
