---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./externalsecret.yaml
- ./helmrepository.yaml
- ./helmrelease.yaml
- ./httproute.yaml
- ./job-cloudnative-pg-bucket.yaml
- ./persistentvolume.yaml
- ./persistentvolumeclaim.yaml
