apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hive-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hive-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: hive
        password: "{{ .DATABASE_PASSWORD }}"
  data:
  - secretKey: DATABASE_PASSWORD
    remoteRef:
      key: hive
      property: DATABASE_PASSWORD
