---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    receiver: telegram
    repeatInterval: 12h
    groupBy:
    - alertname
    - cluster
    - job
    groupInterval: 5m
    groupWait: 1m

  inhibitRules:
  - equal:
    - alertname
    - namespace
    sourceMatch:
    - name: severity
      value: critical
      matchType: =
    targetMatch:
    - name: severity
      value: warning
      matchType: =

  receivers:
  - name: telegram
    telegramConfigs:
    - botToken:
        name: alertmanager-secret
        key: TELEGRAM_BOT_TOKEN
      chatID: 8580477808
      parseMode: HTML
      sendResolved: true
