---
apiVersion: v1
kind: Service
metadata:
  name: minio-console-lan
  annotations:
    lbipam.cilium.io/ips: 192.168.1.205
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: minio
    release: minio
  ports:
  - name: http
    port: 80
    targetPort: 9001
