---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: minio-appdata-pv
