---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-appdata-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
    - nconnect=16
    - hard
    - noatime
  nfs:
    server: 192.168.1.17
    path: /mnt/oasis/Appdata/minio
