---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/tailscale.com/connector_v1alpha1.json
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-subnet-router
spec:
  hostnamePrefix: homelab-subnet-router
  replicas: 1
  subnetRouter:
    advertiseRoutes:
    - 192.168.1.0/24
