---
apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-subnet-router
spec:
  replicas: 1
  hostnamePrefix: homelab-subnet-router
  subnetRouter:
    advertiseRoutes:
    - "192.168.1.0/24"
