apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hive
  namespace: agents
spec:
  dependsOn:
  - name: hive-db
    namespace: database
  interval: 1h
  path: ./kubernetes/apps/agents/hive/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: agents
  wait: true
