apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopiur-repository
    template:
      type: Opaque
      data:
        KOPIA_USERNAME: "{{ .KOPIA_USERNAME }}"
        KOPIA_PASSWORD: "{{ .KOPIA_REPOSITORY_PASSWORD }}"
        KOPIA_SERVER_PASSWORD: "{{ .KOPIA_SERVER_PASSWORD }}"
  dataFrom:
  - extract:
      key: kopiur
