---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kopiur-ui
spec:
  hostnames:
    - kopia.timcasa.me
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: nas-primary-kopia-ui
          port: 51515
