apiVersion: kopiur.home-operations.com/v1alpha1
kind: ClusterRepository
metadata:
  name: nas-primary
spec:
  backend:
    filesystem:
      path: /repo
      volume:
        nfs:
          server: 192.168.1.17
          path: /mnt/oasis/Backups/kopia
  allowedNamespaces:
    list:
    - backups
    - media
    - productivity
  encryption:
    passwordSecretRef:
      name: kopiur-repository
      namespace: backups
      key: KOPIA_PASSWORD
  credentialProjection:
    allowed: true
  server:
    readOnly: true
    namespace: backups
    auth:
      secretRef:
        name: kopiur-repository
        usernameKey: KOPIA_USERNAME
        passwordKey: KOPIA_SERVER_PASSWORD
    service:
      type: ClusterIP
      port: 51515
  create:
    enabled: true
  bootstrap:
    failurePolicy:
      activeDeadlineSeconds: 7200
