---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: timcasa-me-tls
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: timcasa-me-tls
    template:
      type: kubernetes.io/tls
  dataFrom:
  - extract:
      key: timcasa-me-tls
      decodingStrategy: Base64
