---
- name: Nuke dockercompose
  hosts: pihole
  any_errors_fatal: true
  become: false
  gather_facts: true

  tasks:
    - name: Check if apps directory exists
      ansible.builtin.stat:
        path: "{{ pihole_root }}"
      register: apps_dir

    - name: Tear down docker compose services
      community.docker.docker_compose_v2:
        project_src: "{{ pihole_root }}"
        state: absent
        remove_orphans: true
        remove_volumes: false
      become: true
      when: apps_dir.stat.exists
