---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: minio-secret
    template:
      engineVersion: v2
      data:
        rootUser: "{{ .MINIO_ROOT_USER }}"
        rootPassword: "{{ .MINIO_ROOT_PASSWORD }}"
  dataFrom:
  - extract:
      key: minio
