---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-files-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
  - nfsvers=4.1
  nfs:
    server: 192.168.1.17
    path: /mnt/oasis/Docs/vaultwarden
  claimRef:
    namespace: productivity
    name: vaultwarden
