---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        NEXTCLOUD_ADMIN_USER: "{{ .NEXTCLOUD_ADMIN_USER }}"
        NEXTCLOUD_ADMIN_PASSWORD: "{{ .NEXTCLOUD_ADMIN_PASSWORD }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
  dataFrom:
  - extract:
      key: nextcloud
