---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-files-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.17
    path: /mnt/oasis/Documents/nextcloud
  claimRef:
    namespace: productivity
    name: nextcloud-files
