---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: openebs-hostpath

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-apps
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-hostpath
