---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: airflow-pg-credentials
    template:
      engineVersion: v2
      data:
        username: airflow
        password: "{{ .AIRFLOW_DB_PASSWORD }}"
  dataFrom:
  - extract:
      key: airflow
