---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-logs
  namespace: observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
  volumeName: victoria-logs-appdata-pv
