---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-kafka-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: strimzi
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
  values:
    watchAnyNamespace: true
    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        memory: 512Mi
