---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: vaultwarden-db-password
spec:
  generator:
    passwordSpec:
      length: 48
      digits: 10
      symbols: 0
      noUpper: false
      allowRepeat: true
      encoding: base64url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-db
spec:
  refreshInterval: 1h
  target:
    name: vaultwarden-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: vaultwarden
        password: "{{ .password }}"
        DATABASE_URL: "postgresql://vaultwarden:{{ .password }}@postgres0-rw.database.svc.cluster.local:5432/vaultwarden"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: vaultwarden-db-password
