---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: airflow-secret
    template:
      engineVersion: v2
      data:
        fernet-key: "{{ .AIRFLOW_FERNET_KEY }}"
        webserver-secret-key: "{{ .AIRFLOW_WEBSERVER_SECRET_KEY }}"
        admin-password: "{{ .AIRFLOW_ADMIN_PASSWORD }}"
  dataFrom:
  - extract:
      key: airflow
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: airflow-metadata
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: airflow-metadata-secret
    template:
      engineVersion: v2
      data:
        connection: "postgresql://airflow:{{ .AIRFLOW_DB_PASSWORD }}@airflow-pg-rw:5432/airflow"
  dataFrom:
  - extract:
      key: airflow
