---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .POSTGRES_SUPER_USER }}"
        password: "{{ .POSTGRES_SUPER_PASS }}"
        aws-access-key-id: "{{ .RUSTFS_ACCESS_KEY }}"
        aws-secret-access-key: "{{ .RUSTFS_SECRET_KEY }}"
  dataFrom:
  - extract:
      key: cloudnative-pg
  - extract:
      key: rustfs
