---
- Network:
    - Router:
        - href: http://192.168.1.1
          icon: router.png
    - Plex LAN:
        - href: http://192.168.1.210:32400/web
          icon: plex.png
    - Internal Gateway:
        - href: http://192.168.1.200
          icon: envoy.png
