---
- datetime:
    text_size: xl
    locale: en-GB
    format:
      dateStyle: medium
      timeStyle: medium
      timeZone: Europe/Paris
      hour12: false
- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
    nodes:
      show: true
      cpu: true
      memory: true
