apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sensei-read-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sensei-read-only
subjects:
- kind: ServiceAccount
  name: sensei
  namespace: agents
