apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}-config
spec:
  repository:
    kind: ClusterRepository
    name: nas-primary
  sources:
  - pvc:
      name: ${APP}
  retention:
    keepWeekly: 1
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotSchedule
metadata:
  name: ${APP}-config-nightly
spec:
  policyRef:
    name: ${APP}-config
  schedule:
    cron: "H 3 * * 0"
    jitter: 30m
    runOnCreate: false
