---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: tailscale-operator-secret
    template:
      data:
        TAILSCALE_OAUTH_CLIENT_ID: "{{ .TAILSCALE_OAUTH_CLIENT_ID }}"
        TAILSCALE_OAUTH_CLIENT_SECRET: "{{ .TAILSCALE_OAUTH_CLIENT_SECRET }}"
  dataFrom:
  - extract:
      key: tailscale
