apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: anton-db
spec:
  dependsOn:
  - name: cloudnative-pg
  - name: onepassword
    namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/database/anton/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: true
