# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  chartRef:
    kind: OCIRepository
    name: kyverno
  interval: 1h
  values:
    admissionController:
      enabled: false
    backgroundController:
      enabled: false
    cleanupController:
      replicas: 1
      resources:
        limits:
          memory: 256Mi
    reportsController:
      enabled: false
