---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-widgets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-widgets
  data:
    - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
      remoteRef:
        key: sonarr
        property: SONARR_API_KEY
    - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
      remoteRef:
        key: radarr
        property: RADARR_API_KEY
    - secretKey: HOMEPAGE_VAR_PROWLARR_API_KEY
      remoteRef:
        key: prowlarr
        property: PROWLARR_API_KEY
    - secretKey: HOMEPAGE_VAR_SABNZBD_API_KEY
      remoteRef:
        key: sabnzbd
        property: SABNZBD_API_KEY
    - secretKey: HOMEPAGE_VAR_PIHOLE_PASSWORD
      remoteRef:
        key: pihole
        property: PIHOLE_PASSWORD
    - secretKey: HOMEPAGE_VAR_PLEX_TOKEN
      remoteRef:
        key: plex
        property: PLEX_TOKEN
    - secretKey: HOMEPAGE_VAR_FILEBROWSER_USERNAME
      remoteRef:
        key: filebrowser
        property: FB_USERNAME
    - secretKey: HOMEPAGE_VAR_FILEBROWSER_PASSWORD
      remoteRef:
        key: filebrowser
        property: FB_PASSWORD
    - secretKey: HOMEPAGE_VAR_TRUENAS_API_KEY
      remoteRef:
        key: truenas
        property: API_KEY
    - secretKey: HOMEPAGE_VAR_QBITTORRENT_API_KEY
      remoteRef:
        key: qbittorrent
        property: QBITTORRENT_API_KEY
    - secretKey: HOMEPAGE_VAR_TAILSCALE_API_KEY
      remoteRef:
        key: tailscale-homepage
        property: TAILSCALE_API_KEY
    - secretKey: HOMEPAGE_VAR_TAILSCALE_DEVICE_ID
      remoteRef:
        key: tailscale-homepage
        property: TAILSCALE_DEVICE_ID
